kube-state-metrics:
  metricLabelsAllowlist:
    - nodes=[topology.kubernetes.io/region,topology.kubernetes.io/zone]

grafana:
  enabled: true

  grafana.ini:
    server:
      domain: grafana.lab.christiaan.cloud
      root_url: "%(protocol)s://%(domain)s/"
      serve_from_sub_path: false

  defaultDashboardsTimezone: cet

  admin:
    existingSecret: grafana
    userKey: admin-user
    passwordKey: admin-password

  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

  persistence:
    enabled: true
    type: sts
    storageClassName: hcloud-volumes
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection

  ingress:
    enabled: false
    ingressClassName: tailscale
    hosts:
      - grafana
    paths:
      - /
    pathType: Prefix

alertmanager:
  enabled: true

  service:
    type: ClusterIP
    port: 9093
    targetPort: 9093

  ingress:
    enabled: false
    ingressClassName: tailscale
    hosts:
      - alertmanager
    paths:
      - /
    pathType: Prefix