apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 10Gi