apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-pihole
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: pihole-vault-auth
  namespace: pihole
spec:
  kubernetes:
    role: vso-pihole
    serviceAccount: vso-pihole
  vaultAuthGlobalRef:
    allowDefault: true
    namespace: platform