apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-proxy
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - envoy-gateway-system
  selector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: cloudlab
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics