apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-proxy
  namespace: envoy-gateway-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: cloudlab
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics