apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-helm
      app.kubernetes.io/component: envoy-gateway
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics