apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hcloud-csi
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: hcloud-csi
      version: "2.18.0"
      sourceRef:
        kind: HelmRepository
        name: hcloud-csi
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: hetzner-csi-values
      valuesKey: hetzner-csi-values.yaml