apiVersion: v1
kind: Service
metadata:
  name: hashicorp-vault-ui-ts
  namespace: platform
spec:
  selector:
    app.kubernetes.io/name: vault
  ports:
    - name: https
      port: 443
      targetPort: 8200
  type: ClusterIP
