apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
namePrefix: green-
resources:
  - ../../../base/podinfo
transformers:
  - labels.yaml
patchesStrategicMerge:
  - patch.yaml