# overlays/blue/labels.yaml
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  env: development
  instance: podinfo
  version: green
fieldSpecs:
  - path: metadata/labels
    create: true
  - path: spec/selector/matchLabels
    create: true
    kind: Deployment
  - path: spec/template/metadata/labels
    create: true
    kind: Deployment
  - path: spec/selector
    create: true
    kind: Service