apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-deployment
spec:
  template:
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.9.2
          env:
            - name: PODINFO_UI_COLOR
              value: "#057a55"
            - name: PODINFO_UI_MESSAGE
              value: "green"