apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: tailscale-vault-auth
  namespace: tailscale
spec:
  kubernetes:
    role: vso-tailscale
    serviceAccount: tailscale
  vaultAuthGlobalRef:
    allowDefault: true
    namespace: tailscale