apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-internal-ca
  namespace: platform
spec:
  isCA: true
  commonName: vault.internal.ca
  secretName: vault-internal-ca
  issuerRef:
    kind: Issuer
    name: vault-selfsigned-bootstrap
