apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-tls
  namespace: apps
spec:
  secretName: vault-server-tls
  issuerRef:
    kind: Issuer
    name: vault-internal-ca-issuer
  dnsNames:
    - hashicorp-vault.apps.svc
    - hashicorp-vault.apps.svc.cluster.local
    - "*.apps.svc"
    - "*.apps.svc.cluster.local"
  usages:
    - digital signature
    - key encipherment
    - server auth
