apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 10m
  timeout: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.92.4"
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 5m
  values:
    operatorConfig:
      logging: debug

  #valuesFrom:
  #  - kind: ConfigMap
  #    name: vault-values
  #    valuesKey: values.yaml
