---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-storage-hcloud-csi-development
  namespace: flux-system
spec:
  interval: 60s
  path: ./gitops/infrastructure/development/storage/hcloud-csi
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
