apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-vault-secrets-operator-development
  namespace: flux-system
spec:
  interval: 60s
  path: ./gitops/platform/development/hashicorp-vault-secrets-operator
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: platform-vault-development